drop database if exists LOCADORA;
create DATABASE LOCADORA;
use LOCADORA;

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	CPF VARCHAR (11) NOT NULL,
    SEXO VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE,
    ATIVO BOOLEAN,
	PRIMARY KEY (IDFUNCIONARIO)
);

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
    CNH VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
    SEXO VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	PRIMARY KEY (IDCLIENTE)
);
  
CREATE TABLE CARRO (
	IDCARRO INT NOT NULL AUTO_INCREMENT,
	MARCA VARCHAR(255) NOT NULL,
    MODELO varchar(255) NOT NULL,
	ANO CHAR(4) NOT NULL,
	PLACA VARCHAR(8) NOT NULL,
    COR VARCHAR(40) NOT NULL,
	DISPONIBILIDADE BOOLEAN,
    ATIVO BOOLEAN,
	PRIMARY KEY (IDCARRO)
);
    
CREATE TABLE LOCACAO(
	IDLOCACAO INT NOT NULL AUTO_INCREMENT,
	IDCLIENTE INT NOT NULL,
	IDCARRO INT NOT NULL,
	DATA_LOCACAO DATE NOT NULL,
	DATA_PREVISTA_DEVOLUCAO DATE NOT NULL,
	DATA_EFETIVA_DEVOLUCAO DATE,
    VALOR_PREVISTO DOUBLE NOT NULL, 
    VALOR_EFETIVO DOUBLE, 
	MULTA DOUBLE,
    ESTADO BOOLEAN,
	PRIMARY KEY (IDLOCACAO),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
	FOREIGN KEY (IDCARRO) REFERENCES CARRO(IDCARRO)
);

-- DMLs (inserção de registros);

-- select * from locacao;

INSERT INTO CARRO (MARCA, MODELO, ANO, PLACA, COR, DISPONIBILIDADE, ATIVO) VALUES ('FIAT', 'PALIO', 2014, 'MIT5050', 'BRANCO', TRUE, TRUE); 
INSERT INTO CARRO (MARCA, MODELO, ANO, PLACA, COR, DISPONIBILIDADE, ATIVO) VALUES ('VOLKSWAGEN', 'GOL', 2010, 'MIT1050', 'VERDE', TRUE, TRUE); 
INSERT INTO CARRO (MARCA, MODELO, ANO, PLACA, COR, DISPONIBILIDADE, ATIVO) VALUES ('VOLKSWAGEN', 'GOL', 2020, 'MIT8050', 'PRETO', TRUE, TRUE); 

-- YYYY-MM-DD

INSERT INTO CLIENTE (NOME, CNH, CPF, SEXO, DATA_NASCIMENTO, TELEFONE) VALUES ('Leo', '123123312', '09009009009', 'Masculino', '2002-10-30', '48998484848');
INSERT INTO CLIENTE (NOME, CNH, CPF, SEXO, DATA_NASCIMENTO, TELEFONE) VALUES ('Pedro', '123123312', '09009009009', 'Masculino', '2002-10-30', '48998484848');
INSERT INTO CLIENTE (NOME, CNH, CPF, SEXO, DATA_NASCIMENTO, TELEFONE) VALUES ('João', '123123312', '09009009009', 'Masculino', '2002-10-30', '48998484848');

INSERT INTO FUNCIONARIO(NOME, SENHA, CPF, SEXO, DATA_NASCIMENTO, TELEFONE, ATIVO) VALUES ('Leo', '12345', '09009009009', 'Masculino', '2002-10-30', '48998484848', TRUE);
INSERT INTO FUNCIONARIO (NOME, SENHA, CPF, SEXO, DATA_NASCIMENTO, TELEFONE, ATIVO) VALUES ('Pedro', '12345',  '09009009009', 'Masculino', '2002-10-30', '48998484848', TRUE);
INSERT INTO FUNCIONARIO (NOME, SENHA, CPF, SEXO, DATA_NASCIMENTO, TELEFONE, ATIVO) VALUES ('João', '12345',  '09009009009', 'Masculino', '2002-10-30', '48998484848', TRUE);

SELECT * FROM CARRO;
SELECT * FROM LOCACAO;
SELECT * FROM CLIENTE;

SELECT * FROM CARRO WHERE DISPONIBILIDADE = TRUE AND ATIVO = TRUE;



